import {
  HiOutlineHome,
  HiOutlineUsers,
  HiOutlineCog,
  HiOutlineShoppingCart,
  HiOutlineCube,
  HiOutlineTruck,
  HiOutlineCamera,
  HiOutlineGlobe,
  HiOutlineCurrencyDollar,
  HiOutlineDocumentText,
  HiOutlineChartBar,
  HiOutlineUserGroup,
  HiOutlineGift,
  HiOutlineStar,
  HiOutlineClipboardList,
  HiOutlineEye,
  HiOutlineQrcode,
  HiOutlineUserAdd,
  HiOutlineClock,
  HiOutlineCollection,
  HiOutlineCash,
} from 'react-icons/hi';
import { ROLES } from './roles';

export const menuPorRol = {
  [ROLES.SUPER_ADMINISTRADOR]: [
    { label: 'Dashboard', path: '/super-administrador/dashboard', icon: HiOutlineHome },
    { label: 'Usuarios', path: '/super-administrador/usuarios', icon: HiOutlineUsers },
    { label: 'Configuración', path: '/super-administrador/configuracion', icon: HiOutlineCog },
    { label: 'Combos', path: '/super-administrador/combos', icon: HiOutlineCollection },
    { label: 'Landing Page', path: '/super-administrador/config-landing', icon: HiOutlineGlobe },
    { label: 'Ventas', path: '/administrador/ventas', icon: HiOutlineShoppingCart },
    { label: 'Clientes', path: '/administrador/clientes', icon: HiOutlineUsers },
    { label: 'Productos', path: '/administrador/productos', icon: HiOutlineCube },
    { label: 'Config. Precios', path: '/administrador/configuracion-precios', icon: HiOutlineCurrencyDollar },
    { label: 'Inventario', path: '/administrador/inventario', icon: HiOutlineClipboardList },
    { label: 'Importaciones', path: '/administrador/importaciones', icon: HiOutlineGlobe },
    { label: 'Compras', path: '/administrador/compras', icon: HiOutlineShoppingCart },
    { label: 'Proveedores', path: '/administrador/proveedores', icon: HiOutlineTruck },
    { label: 'Caja', path: '/administrador/caja', icon: HiOutlineCurrencyDollar },
    { label: 'Promociones', path: '/administrador/promociones', icon: HiOutlineGift },
    { label: 'Puntos', path: '/administrador/puntos', icon: HiOutlineStar },
    { label: 'RRHH', path: '/administrador/rrhh', icon: HiOutlineUserGroup },
    { label: 'Reportes', path: '/administrador/reportes', icon: HiOutlineChartBar },
    { label: 'Almacenes', path: '/administrador/almacenes', icon: HiOutlineCube },
    { label: 'Análisis Mkt', path: '/administrador/analisis-marketing', icon: HiOutlineChartBar },
    { label: 'Transportistas', path: '/administrador/transportistas', icon: HiOutlineTruck },
    { label: 'Facturación', path: '/administrador/config-facturacion', icon: HiOutlineDocumentText },
  ],
  [ROLES.ADMINISTRADOR]: [
    { label: 'Dashboard', path: '/administrador/dashboard', icon: HiOutlineHome },
    { label: 'Ventas', path: '/administrador/ventas', icon: HiOutlineShoppingCart },
    { label: 'Clientes', path: '/administrador/clientes', icon: HiOutlineUsers },
    { label: 'Productos', path: '/administrador/productos', icon: HiOutlineCube },
    { label: 'Config. Precios', path: '/administrador/configuracion-precios', icon: HiOutlineCurrencyDollar },
    { label: 'Inventario', path: '/administrador/inventario', icon: HiOutlineClipboardList },
    { label: 'Importaciones', path: '/administrador/importaciones', icon: HiOutlineGlobe },
    { label: 'Compras', path: '/administrador/compras', icon: HiOutlineShoppingCart },
    { label: 'Proveedores', path: '/administrador/proveedores', icon: HiOutlineTruck },
    { label: 'Caja', path: '/administrador/caja', icon: HiOutlineCurrencyDollar },
    { label: 'Promociones', path: '/administrador/promociones', icon: HiOutlineGift },
    { label: 'Puntos', path: '/administrador/puntos', icon: HiOutlineStar },
    { label: 'RRHH', path: '/administrador/rrhh', icon: HiOutlineUserGroup },
    { label: 'Reportes', path: '/administrador/reportes', icon: HiOutlineChartBar },
    { label: 'Almacenes', path: '/administrador/almacenes', icon: HiOutlineCube },
    { label: 'Análisis Mkt', path: '/administrador/analisis-marketing', icon: HiOutlineChartBar },
    { label: 'Transportistas', path: '/administrador/transportistas', icon: HiOutlineTruck },
    { label: 'Facturación', path: '/administrador/config-facturacion', icon: HiOutlineDocumentText },
  ],
  [ROLES.SECRETARIA]: [
    { label: 'Dashboard', path: '/secretaria/dashboard', icon: HiOutlineHome },
    { label: 'Facturación', path: '/secretaria/facturas', icon: HiOutlineDocumentText },
    { label: 'Ventas', path: '/secretaria/ventas', icon: HiOutlineShoppingCart },
    { label: 'Reportes', path: '/secretaria/reportes', icon: HiOutlineChartBar },
    { label: 'RRHH', path: '/secretaria/rrhh', icon: HiOutlineUserGroup },
  ],
  [ROLES.SUPERVISION_VENTA]: [
    { label: 'Dashboard', path: '/supervision/dashboard', icon: HiOutlineHome },
    { label: 'Ventas', path: '/supervision/ventas', icon: HiOutlineEye },
    { label: 'Reportes', path: '/supervision/reportes', icon: HiOutlineChartBar },
    { label: 'Transportistas', path: '/administrador/transportistas', icon: HiOutlineTruck },
    { label: 'Configuración', path: '/supervision/configuracion', icon: HiOutlineCog },
  ],
  [ROLES.VENDEDOR]: [
    { label: 'Dashboard', path: '/vendedor/dashboard', icon: HiOutlineHome },
    { label: 'Ventas', path: '/vendedor/ventas', icon: HiOutlineShoppingCart },
    { label: 'Combos', path: '/vendedor/combos', icon: HiOutlineCollection },
    { label: 'Clientes', path: '/vendedor/clientes', icon: HiOutlineUsers },
    { label: 'Inventario', path: '/vendedor/inventario', icon: HiOutlineClipboardList },
    { label: 'Banco Fotos', path: '/vendedor/banco-fotos', icon: HiOutlineCamera },
    { label: 'Cotizaciones', path: '/vendedor/cotizaciones', icon: HiOutlineDocumentText },
    { label: 'Prospectos', path: '/vendedor/prospectos', icon: HiOutlineUserAdd },
    { label: 'Mis Comisiones', path: '/vendedor/comisiones', icon: HiOutlineCash },
  ],
  [ROLES.ALMACEN]: [
    { label: 'Dashboard', path: '/almacen/dashboard', icon: HiOutlineHome },
    { label: 'Recepción', path: '/almacen/recepcion', icon: HiOutlineClipboardList },
    { label: 'Recep. Importaciones', path: '/almacen/recepcion-importaciones', icon: HiOutlineGlobe },
    { label: 'Despacho', path: '/almacen/despacho', icon: HiOutlineTruck },
    { label: 'Escáner de Salida', path: '/almacen/escaner-salida', icon: HiOutlineQrcode },
    { label: 'Banco Fotos', path: '/almacen/banco-fotos', icon: HiOutlineCamera },
    { label: 'Inventario', path: '/almacen/inventario', icon: HiOutlineCube },
  ],
  [ROLES.CHOFER]: [
    { label: 'Dashboard', path: '/chofer/dashboard', icon: HiOutlineHome },
    { label: 'Entregas', path: '/chofer/entregas', icon: HiOutlineTruck },
    { label: 'Compras disponibles', path: '/chofer/compras-disponibles', icon: HiOutlineShoppingCart },
  ],
  [ROLES.CONTROL_ASISTENCIA]: [
    { label: 'Dashboard', path: '/control-asistencia/dashboard', icon: HiOutlineHome },
    { label: 'Escáner QR', path: '/control-asistencia/escaner', icon: HiOutlineQrcode },
    { label: 'Historial', path: '/control-asistencia/historial', icon: HiOutlineClipboardList },
  ],
  [ROLES.CLIENTE]: [
    { label: 'Dashboard', path: '/cliente/dashboard', icon: HiOutlineHome },
    { label: 'Catálogo', path: '/catalogo', icon: HiOutlineCube },
    { label: 'Próx. Ingresos', path: '/cliente/proximos-ingresos', icon: HiOutlineClock },
    { label: 'Mis Pedidos', path: '/cliente/pedidos', icon: HiOutlineShoppingCart },
    { label: 'Tracking', path: '/cliente/tracking', icon: HiOutlineTruck },
    { label: 'Mis Puntos', path: '/cliente/puntos', icon: HiOutlineStar },
  ],
};
